const products = [
  ['Haven Guest Signal Engine™', 'Captures guest preferences, behaviors, and signals across every touchpoint — so the hotel always knows who is arriving and what they need.'],
  ['Haven Recovery Engine™', 'Turns service failures into loyalty moments. Detects issues in real time and routes recovery actions before a guest has to complain.'],
  ['Haven Smart Routing™', 'Routes guest requests, signals, and tasks to the right department automatically — no manual triage required.'],
  ['Haven Auto Dispatch™', 'Autonomous agent dispatch that acts on guest signals without waiting for a staff member to notice.'],
  ['Haven Guest Link™', 'A frictionless QR-based guest intake system that begins building the memory relationship from the moment of arrival.'],
  ['Haven Proof Engine™', 'Validates performance and generates evidence of service quality — so hotels can measure what their memory infrastructure is actually doing.'],
] as const

const statuses = [
  ['IHG One Rewards', 'Royal Ambassador', 'Invite-only. IHG selects the member — it cannot be purchased or applied for.'],
  ['Kimpton Hotels', 'Inner Circle', 'Invite-only. Kimpton notices and invites — no application process exists.'],
  ['Marriott Bonvoy', 'Ambassador Elite', 'Highest publicly available tier. Requires $20,000+ spend and 100+ nights annually.'],
  ['Hilton Honors', 'Diamond', 'Top tier. Requires 30+ stays or 60+ nights annually.'],
  ['World of Hyatt', 'Discoverist', 'Earned through qualifying nights and activity.'],
  ['Accor Live Limitless', 'Limitless Platinum', "Top tier across Accor's global portfolio."],
  ['Choice Privileges', 'Platinum', 'Highest tier in the Choice Hotels loyalty program.'],
] as const

export default function FounderStory() {
  return <div className="bg-haven-navy text-white">
    <section className="mx-auto max-w-4xl px-6 pb-16 pt-20 text-center md:pt-28"><div className="eyebrow mb-5">Founder story &amp; origin</div><h1 className="text-4xl font-bold leading-tight md:text-6xl">The Problem No One Had Named</h1><figure className="mx-auto mt-9 max-w-xs md:max-w-sm"><img src="/nathaniel-clarke.png" alt="Nathaniel Clarke, founder of HCCGSA LLC, holding the &quot;Saving the Youth&quot; award at the Global Leadership Awards" className="w-full rounded-lg border border-haven-gold/25 shadow-lg" width={1148} height={1370} /><figcaption className="mt-3 text-sm italic leading-6 text-white/55">Nathaniel Clarke received the &quot;Saving the Youth&quot; honor at the Global Leadership Awards.</figcaption></figure><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-white/75">Every major hotel brand in the world has a loyalty program. Independent hotels have none of that infrastructure — and every time a guest checks in, the hotel starts from zero. Nathaniel Clarke called this <strong className="text-white">Institutional Alzheimer&apos;s</strong>. Then he built the solution.</p></section>
    <div className="mx-auto max-w-3xl border-t border-haven-gold/25" />
    <section className="mx-auto max-w-3xl space-y-5 px-6 py-16"><h2 className="text-3xl font-bold text-haven-gold">Where the Insight Came From</h2><p className="prose-copy text-white/80">Nathaniel Clarke didn&apos;t read about the problem in a report. He lived it — across every major hotel brand in the world, at the highest tier each program offers.</p><p className="prose-copy text-white/80">At that level, recognition is not a perk. It is a standard. Staff know your name before you arrive. Your preferences are waiting for you. The experience is continuous across every property, every city, every stay. <strong className="text-white">That continuity is the product.</strong></p><p className="prose-copy text-white/80">Independent boutique hotels — often the most beautiful, most personal properties in the world — cannot replicate that. Not because their staff don&apos;t care. Because the infrastructure to remember doesn&apos;t exist for them. Every new guest, every new stay, every new interaction begins from nothing.</p><p className="prose-copy text-white/80">Nathaniel named this gap <strong className="text-white">Institutional Alzheimer&apos;s</strong> — the condition of a hotel that forgets every guest the moment they leave. He began developing the concept in late 2024. Haven Memory OS™ is the answer.</p></section>
    <section className="bg-white/5"><div className="mx-auto max-w-3xl px-6 py-16"><h2 className="text-3xl font-bold text-haven-gold">Haven Memory OS™ — The First Guest Intelligence OS</h2><p className="mt-5 leading-8 text-white/80">Haven Memory OS™ is not a CRM. It is not a property management add-on. It is the first operating system built specifically around <strong className="text-white">guest memory</strong> — giving independent hotels the intelligence infrastructure that only the largest brands have ever had.</p><div className="mt-8 grid gap-4">{products.map(([name, description]) => <article key={name} className="border-l-4 border-haven-gold bg-white/5 p-6"><h3 className="text-xl font-bold">{name}</h3><p className="mt-2 text-sm leading-7 text-white/70">{description}</p></article>)}</div><p className="mt-8 leading-8 text-white/80">Haven Memory OS™ is live at <a className="text-haven-gold hover:underline" href="https://haven-mos.org" target="_blank" rel="noopener noreferrer">haven-mos.org</a> with a 60-day free trial for qualifying independent hotels.</p></div></section>
    <section className="mx-auto max-w-4xl px-6 py-16"><h2 className="text-3xl font-bold text-haven-gold">Global Elite Loyalty Credentials</h2><p className="mt-5 leading-8 text-white/80">The foundation of Haven Memory OS™ is not theory. It is firsthand mastery of how the world&apos;s best hotel programs deliver recognition at the highest level.</p><p className="mt-5 text-sm italic leading-7 text-white/55">Nathaniel Clarke formerly held elite status across every major global hotel loyalty program — at the invitation-only and top-tier levels. These statuses are earned through qualifying activity and lapse when that activity stops; they are listed here as the experiential foundation from which the Institutional Alzheimer&apos;s concept and Haven Memory OS™ were developed.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{statuses.map(([brand, status, note]) => <article key={brand} className="border border-haven-gold/25 bg-white/5 p-5"><div className="eyebrow text-[10px]">{brand}</div><h3 className="mt-2 text-lg font-bold">{status}</h3><p className="mt-2 text-xs italic leading-5 text-white/50">{note}</p></article>)}</div><p className="mt-6 text-xs italic leading-6 text-white/45">Elite statuses are activity-based and lapse when qualifying activity ceases. The statuses above reflect the firsthand hospitality experience that informed the development of Haven Memory OS™ and the Institutional Alzheimer&apos;s framework.</p></section>
    <section className="bg-haven-gold/10"><div className="mx-auto max-w-3xl px-6 py-16"><h2 className="text-3xl font-bold text-haven-gold">About the Founder</h2><div className="mt-7 border border-haven-gold/25 bg-haven-gold/10 p-7 leading-8 text-white/85"><p>Nathaniel Clarke is the Founder and CEO of HCCGSA LLC — Hotel Chamber of Commerce, Guest Services Advocacy LLC — incorporated in Philadelphia and operating from New York.</p><p className="mt-4">HCCGSA LLC operates under the methodology brand <strong className="text-white">ARCHITEK N ADVOCACY™</strong> and runs a multi-product portfolio spanning hospitality technology, civic technology, fintech, and consumer health.</p><p className="mt-4">The work begins from a simple conviction: the best independent hotels in the world deserve the same intelligence infrastructure as the largest chains. Haven Memory OS™ exists to close that gap — one hotel, one guest, one remembered moment at a time.</p><span className="mt-5 block font-bold text-haven-gold">— Nathaniel Clarke · ARCHITEK N ADVOCACY™</span></div></div></section>
  </div>
}
