import { Link } from 'react-router-dom'
import SealBadge from '../components/SealBadge'
import SectionLabel from '../components/SectionLabel'
import StatCard from '../components/StatCard'
import ProductCard from '../components/ProductCard'

export default function Home() { return <div>
  <section className="bg-haven-navy px-6 py-24 text-white md:py-32"><div className="mx-auto max-w-5xl text-center"><SealBadge size="lg" /><SectionLabel>HCCGSA LLC · ARCHITEK N ADVOCACY</SectionLabel><h1 className="mt-5 text-4xl font-bold leading-tight md:text-6xl">Building stronger hotels.<br />Empowering people.<br /><span className="text-haven-gold">Elevating hospitality.</span></h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-white/70">We build AI-powered operating systems and practical technology for independent hotels, food service operators, housing advocates, and compliance professionals.</p><div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row"><a href="https://haven-mos.org/pricing" className="bg-haven-gold px-8 py-3 text-center font-bold text-haven-navy transition hover:bg-yellow-300">Start Free 60-Day Pilot →</a><a href="https://haven-mos.org" className="border border-haven-gold px-8 py-3 text-center font-bold text-haven-gold transition hover:bg-haven-gold hover:text-haven-navy">See the Platform</a></div></div></section>
  <section className="bg-haven-gold px-6 py-12"><div className="mx-auto max-w-4xl text-center"><p className="text-xl font-bold leading-8 text-haven-navy">“Guests deserve to be remembered. Independent hotels deserve a fighting chance. We build the technology to make both possible.”</p><p className="mt-3 text-sm font-semibold text-haven-navy">— Nathaniel Clarke, Founder and CEO</p></div></section>
  <section className="bg-haven-navy px-6 py-20 text-white"><div className="mx-auto max-w-4xl"><SectionLabel>The problem we named</SectionLabel><h2 className="text-3xl font-bold md:text-4xl">Institutional Alzheimer’s</h2><div className="mt-8 space-y-5 border-l-4 border-haven-gold pl-6 text-lg leading-8 text-white/70"><p>Every time a hotel shift changes, the organization forgets.</p><p>A guest reports a cold shower at 2pm. A new crew walks in at 11pm and knows nothing. The guest calls down again, explains everything from scratch, and checks out without saying anything.</p><p>We named this condition—the systematic loss of institutional memory at every shift change, department boundary, and personnel transition—and built Haven Memory OS specifically to eliminate it.</p></div><Link to="/haven" className="mt-8 inline-block font-bold text-haven-gold hover:underline">See how Haven fixes this →</Link></div></section>
  <section className="px-6 py-20"><div className="mx-auto max-w-5xl"><div className="mb-12 text-center"><SectionLabel>Validated before we pitched it</SectionLabel><h2 className="text-3xl font-bold text-haven-navy">The evidence</h2><p className="mx-auto mt-3 max-w-xl text-slate-600">Haven was tested across synthetic hotel complaint scenarios using a separate evaluation framework before approaching a single hotel.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><StatCard number="97.5" label="Haven score" sub="out of 100" /><StatCard number="64.0" label="Manual baseline" sub="same conditions" /><StatCard number="+33.5" label="Point improvement" sub="over manual operation" /><StatCard number="0" label="Safety failures" sub="across 60 runs" /></div><p className="mt-6 text-center text-sm text-slate-500">77 audit logs committed to GitHub. Synthetic validation results; real proof begins with pilot data.</p></div></section>
  <section className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-6xl"><div className="mb-12 text-center"><SectionLabel>One methodology. Many solutions.</SectionLabel><h2 className="text-3xl font-bold text-haven-navy">The portfolio</h2></div><div className="grid gap-5 md:grid-cols-3"><ProductCard name="Haven Memory OS" category="Hospitality intelligence" description="Guest Intelligence Operating System for independent boutique hotels. Live at haven-mos.org." href="/haven" /><ProductCard name="FreshSave Pro" category="Food safety" description="Food safety and inventory management for food service operators." /><ProductCard name="Vigilant Revenue Protector" category="Fintech" description="Revenue reconciliation and financial monitoring for operators." /></div><div className="mt-10 text-center"><Link to="/portfolio" className="inline-block bg-haven-navy px-8 py-3 font-bold text-white transition hover:bg-haven-gold hover:text-haven-navy">View the full portfolio →</Link></div></div></section>
  <section className="bg-haven-navy px-6 py-20 text-center text-white"><SealBadge size="md" /><h2 className="mt-6 text-3xl font-bold">Proof before pitch.</h2><p className="mx-auto mt-4 max-w-2xl leading-8 text-white/65">HCCGSA operates under ARCHITEK N ADVOCACY: protect the work, validate the system, and make claims that evidence can carry.</p><div className="mt-8 flex flex-wrap justify-center gap-3">{['HANYC Allied Member 2026', '13 Provisional Patents Filed', 'Research on Zenodo', 'ORCID Registered', 'Est. 2020'].map(item => <span key={item} className="border border-haven-gold px-4 py-2 text-xs font-bold text-haven-gold">{item}</span>)}</div></section>
</div> }
